//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reco4.UI.Module.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoadmapGroups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoadmapGroups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reco4.UI.Module.Properties.RoadmapGroups", typeof(RoadmapGroups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Text.
        /// </summary>
        public static string CellText {
            get {
                return ResourceManager.GetString("CellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Vehicle Input Status.
        /// </summary>
        public static string ConvertToVehicleInputStatus {
            get {
                return ResourceManager.GetString("ConvertToVehicleInputStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy....
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner SSS.
        /// </summary>
        public static string OwnerSSS {
            get {
                return ResourceManager.GetString("OwnerSSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected.
        /// </summary>
        public static string Protected {
            get {
                return ResourceManager.GetString("Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string RoadmapGroupId {
            get {
                return ResourceManager.GetString("RoadmapGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadmap Name.
        /// </summary>
        public static string RoadmapName {
            get {
                return ResourceManager.GetString("RoadmapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Row(s).
        /// </summary>
        public static string SelectedRowOpenBracketCloseBracket {
            get {
                return ResourceManager.GetString("SelectedRowOpenBracketCloseBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Status.
        /// </summary>
        public static string ValidationStatus {
            get {
                return ResourceManager.GetString("ValidationStatus", resourceCulture);
            }
        }
    }
}
